export const gameOfThrones: string = '[name="kp_query"]';
export const clickButton: string = '[href="/film/464963/sr/2/"]';
export const linkToSubscribe: string = 'a.styles_plusDesktopBrandingButton__X4z6T';
export const topSeries: string = '[href="/film/4365427/sr/2/"]';
export const buyingTickets: string = '[class=styles_root__RBtQR] a[href="/afisha/new/"]';
export const randomMovie: string = 'svg.search-form-submit-button__icon';
export const resultImage: string = '[alt="Игра престолов (Game of Thrones)"]';
export const resultSubscribe: string = '[data-tid="2be7a1eb"]';
export const resultRating: string = 'span.styles_listTitle__9G9Q9';
export const checkButton: string = '//div[contains(@class,"myBoardButton ")]//a[text()="Моя афиша"]';
export const resultOfRandom: string = 'input.button';
